addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0
deploy:
  provider: pypi
  skip_cleanup: true
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: mV4VBNhdvUKSm2RmQfb0zEpRezSnpCeAuLmkTO3h6SzmgTwwcdyza3oNr8fet0KhMeRHpiCLyZuW/WMFBUbe70N/ObWA+etQ3WiKnjvQYEk9txEleUYwXwAZMUL4LLv5wTUc/gq211emRcH69ocftmKRfXEx+a5/nnXOWLmUwby1FNe1v08w4ZNdOsLLm99OAjLafa7nkxkvYc1pQ4/fas9kUGK1LYud20NfqrflgIWZnqQlaxVKbAxPkpWAEXAfjH+G/UfpthYCj7WgQtcPKsx4OsXXvjxLi1ZQzLxumNN9hVpcnx4TDxIFX5fjDRxbCwZxkx0R1TNRHq1ftt7KN57/vPdR4FWlaLi2LDL87psUuLz3jqJythfyGa5aX8ZTHW8ErZh90W0GOt4YmOYBsG0873h/1NggpIu/MV3IDyK0DZz1BaB9t7OFryGVoawuehlFRB/4XNfXUX3XeAMi0wFcfQXVwfdxpt4U9w5Krx7M1trNQWLKaWFfKrwKWHUs0AJ6FsHY72m7BeHyaXKW/iS1xaZgvOKWK+256NK7TM7gUqNTiJifmmlD5RmD42gtDdllBIuMKeNtfyWx1AwSFK/WvAvKBaJQcZxHi2sTRMaIbaq+qcUl8V53CS4Ct8FTlyQ0aOHCCXK4DXFwOUPd7XJWhyrm9DDcYL7iR58J7nI=
  edge: true
  on:
    branch: master
    python: '3.7'
    repo: lsst-sitcom/spot_motion_monitor
    tags: true
dist: bionic
install:
- pip install -U pip
- pip install -r requirements.txt
- pip install -r requirements/test.txt
- pip install -U pytest
- python setup.py build_ui
- python setup.py install
language: python
python:
- '3.6'
- '3.7'
script: xvfb-run pytest
sudo: false
